<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBhjFSd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBhjFSd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBhjFSd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBhjFSd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBhjFSd\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBhjFSd',
    'container.build_id' => 'a7b9ed15',
    'container.build_time' => 1594881770,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBhjFSd');
